name: Run tests

on:
  - pull_request

jobs:
  test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
      ALGOLIA_ID: ${{ secrets.ALGOLIA_ID }}
      GA_ID: ${{ secrets.GA_ID }}
      HOTJAR_ID: ${{ secrets.HOTJAR_ID }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: pnpm install
        working-directory: .

      - name: Retrieve Docusaurus build cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/webpack
          key: docusaurus-${{ github.ref_name }}
          restore-keys: |
            docusaurus-${{ github.ref_name }}
            docusaurus-master

      - name: Check build
        run: pnpm build
        working-directory: .

  test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: pnpm install
        working-directory: .

      - name: Retrieve linter cache
        uses: actions/cache@v4
        with:
          path: |
            ./.eslintcache
            ./node_modules/.cache/prettier/.prettier-cache
            ./stylelintcache
          key: linters-${{ github.ref_name }}
          restore-keys: |
            linters-${{ github.ref_name }}
            linters-master

      - name: Check linting
        run: pnpm run test:lint
        working-directory: .
